### ISSUE TITLE
igZoombar buttons

### ISSUE THREAD

**Issue by sberman-eagle** [IgniteUI/igniteui-angular2#119]
http://igniteui.github.io/igniteui-angular2/samples/igDataChart/igDataChart.html
The left and right buttons on igzoombar are not visible, from what I could find when comparing the html generated using angular 1 or javascript vs angular2 the ui-igzoombar-scrollbar div does not have the inner div and spans for the buttons.  
http://www.igniteui.com/zoombar/overview

**Comment by dkamburov** [comment]
Looks like a styling issue, we'll have to investigate this one.

**Comment by sberman-eagle** [comment]
awful but good enough for am upcoming demo:
		$("#"+this.zbWidgetId+"_zoombar_buttons_right").addClass('ui-igzoombar-scrollbar-button ui-button-icon-primary ui-icon ui-icon-triangle-1-e');
		$("#"+this.zbWidgetId+"_zoombar_buttons_left").addClass('ui-igzoombar-scrollbar-button ui-button-icon-primary ui-icon ui-icon-triangle-1-w');

Its actauly adding to the outer class it should append to the div but servers its purpose for now.

**Comment by kdinev** [comment]
@sberman-eagle I am reopening the issue. We will fix it so such workaround isn't necessary!

**Comment by MayaKirova** [comment]
This is actually not an issue with the bootstrap classes. 
It occurs when the bootstrap.js file is referenced on the page, because it contains a function with the name "button" that conflicts with JQuery UI's button, which we internally use to create the buttons: 
http://stackoverflow.com/questions/26180429/jquery-ui-and-bootstrap-button-conflict

This appears to be a third party issue.
We'll fix it in the sample itself.
