### ISSUE TITLE
Igniteui-angular2 with angularcli giving error as Cannot read property 'igGrid' of undefined issue

### ISSUE THREAD

**Issue by rishisharma1510** [IgniteUI/igniteui-angular2#139]
Hi,
I am trying to use igniteui-angular2 igrid with angularcli. I am using Visual Studio Code as IDE
But when i run the application in the browser in chrome i get error as 
Uncaught TypeError: Cannot read property 'igGrid' of undefined
    at index.js:185
    at __decorate (index.js:10)
    at index.js:531
    at Object.s (index.js:536)
    at __webpack_require__ (bootstrap 7e9d76b…:52)
    at Object.489 (app.component.ts:11)
    at __webpack_require__ (bootstrap 7e9d76b…:52)
    at Object.368 (src async:7)
    at __webpack_require__ (bootstrap 7e9d76b…:52)
    at Object.618 (main.bundle.js:343)
    at __webpack_require__ (bootstrap 7e9d76b…:52)
    at webpackJsonpCallback (bootstrap 7e9d76b…:23)
    at main.bundle.js:1
(anonymous) @ index.js:185
__decorate @ index.js:10
(anonymous) @ index.js:531
s @ index.js:536
__webpack_require__ @ bootstrap 7e9d76b…:52
489 @ app.component.ts:11
__webpack_require__ @ bootstrap 7e9d76b…:52
368 @ src async:7
__webpack_require__ @ bootstrap 7e9d76b…:52
618 @ main.bundle.js:343
__webpack_require__ @ bootstrap 7e9d76b…:52
webpackJsonpCallback @ bootstrap 7e9d76b…:23
(anonymous) @ main.bundle.js:1

Could anybody help me in this
[Srcwithsomerequiredfiles.zip](https://github.com/IgniteUI/igniteui-angular2/files/831446/Srcwithsomerequiredfiles.zip)

**Comment by rishisharma1510** [comment]
Could anybody please help in this issue?

**Comment by kdinev** [comment]
@rishisharma1510 Hi there. We're sorry that we still haven't been able to get to investigating this issue. We will look at it within the next couple of days and we will update you.

**Comment by dkamburov** [comment]
@rishisharma1510, you'll have to download include references to igniteui into scripts in `angular-cli.json` file:
```
"scripts": ["../node_modules/jquery/dist/jquery.min.js",
		"../node_modules/jqueryui/jquery-ui.min.js",
		"../igniteui/infragistics.core.js", "../igniteui/infragistics.lob.js" ]
```
Note that reference to jquery-ui is also required

**Comment by roscheld** [comment]
Hello,

I have the same issue but I already added the items to my angular-cli.json

Here is my angular-cli.json. I started from a clean install and just added jquery, jquery-ui and infragistics core and lob.
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "ox-aankoop"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "../node_modules/ignite-ui/css/structure/infragistics.css",
        "../node_modules/ignite-ui/css/themes/infragistics/infragistics.theme.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/jquery-ui-dist/jquery-ui.min.js",
        "../node_modules/ignite-ui/js/infragistics.core-lite.js",
        "../node_modules/ignite-ui/js/infragistics.lob-lite.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}

The error i'm now getting is:

`Unhandled Promise rejection: Template parse errors:
Can't bind to 'widgetId' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'widgetId' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [ERROR ->][(widgetId)]='gridId' [(options)]='gridOptions' [(dataSource)] ='gridData'></ig-grid>"): AppComponent@4:9
Can't bind to 'options' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [(widgetId)]='gridId' [ERROR ->][(options)]='gridOptions' [(dataSource)] ='gridData'></ig-grid>"): AppComponent@4:31
Can't bind to 'dataSource' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'dataSource' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [(widgetId)]='gridId' [(options)]='gridOptions' [ERROR ->][(dataSource)] ='gridData'></ig-grid>"): AppComponent@4:57 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
Can't bind to 'widgetId' since it isn't a known property of 'ig-grid'.…, _nativeError: ZoneAwareError, __zone_symbol__currentTask: ZoneTask, __zone_symbol__stack: "Error: Template parse errors:↵Can't bind to 'widge…ttp://localhost:4200/polyfills.bundle.js:2813:35)", __zone_symbol__message: "Template parse errors:↵Can't bind to 'widgetId' si…rce)] ='gridData'></ig-grid>"): AppComponent@4:57"} Error: Template parse errors:
Can't bind to 'widgetId' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'widgetId' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [ERROR ->][(widgetId)]='gridId' [(options)]='gridOptions' [(dataSource)] ='gridData'></ig-grid>"): AppComponent@4:9
Can't bind to 'options' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [(widgetId)]='gridId' [ERROR ->][(options)]='gridOptions' [(dataSource)] ='gridData'></ig-grid>"): AppComponent@4:31
Can't bind to 'dataSource' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'dataSource' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [(widgetId)]='gridId' [(options)]='gridOptions' [ERROR ->][(dataSource)] ='gridData'></ig-grid>"): AppComponent@4:57
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3259:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:64688:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:5720:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:17572:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:47634:68)
    at http://localhost:4200/vendor.bundle.js:47517:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:47517:19)
    at createResult (http://localhost:4200/vendor.bundle.js:47399:19)
    at ZoneDelegate.webpackJsonp.608.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2601:26)
    at Zone.webpackJsonp.608.Zone.run (http://localhost:4200/polyfills.bundle.js:2393:43)
    at http://localhost:4200/polyfills.bundle.js:2980:57
    at ZoneDelegate.webpackJsonp.608.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2634:31)
    at Zone.webpackJsonp.608.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2433:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2813:35)
consoleError @ zone.js:522
handleUnhandledRejection @ zone.js:527
_loop_1 @ zone.js:562
drainMicroTaskQueue @ zone.js:566
zone.js:524 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'widgetId' since it isn't …, rejection: SyntaxError, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask}`

`

**Comment by dkamburov** [comment]
The lite version of IgniteUI does not contain igGrid
```
"../node_modules/ignite-ui/js/infragistics.core-lite.js",
"../node_modules/ignite-ui/js/infragistics.lob-lite.js"
```

You need to [download ](http://www.infragistics.com/products/jquery) and install the full version infragistics.core.js and infragistics.lob.js

**Comment by roscheld** [comment]
@dkamburov 
Thank you very much! Now it works!

Just had to change the css files because I had issues with them see #96 at the bottom.

**Comment by roscheld** [comment]
Hmm I still have one problem, I can do a normal build but when I want to do a production build it gives an error. See screenshot.

Thanks in advance.

![problemwithprodbuild](https://cloud.githubusercontent.com/assets/7072451/24255266/496aea9c-0fe5-11e7-8917-3d19ecc26e2c.PNG)

**Comment by dkamburov** [comment]
My suggestion would be to check the import statements. IgGridComponent should be imported from index.js while the error says it's trying to import it from index.d.ts.

**Comment by roscheld** [comment]
Where do I need to change that? I tried doing it like this, but it still gives the same error:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { IgGridComponent} from 'igniteui-angular2/index.js';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent,
    IgGridComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by dkamburov** [comment]
Can you demonstrate this in isolated sample with steps to reproduce?

**Comment by roscheld** [comment]
Here you can download my project:

https://we.tl/tdw2wjT7OF

When I do ng server or ng build in my root folder, everything works fine.
But when I do ng build --prod it get the import error.

The only files I changed I already mentioned in the above posts.

I found this in the other issue but don't know how to apply it. And it's not entirely the same because it does find the file in the server and normal build.

> Node can't find the ignite-angular.js file at all. One solution is to rename the igniteui.angular2.js file to index.js, the other one would be to set the main property in the package.json file.

Many thanks for looking into this!

**Comment by gulbdoug** [comment]
try using ng build --prod --aot=false.  I don't think it works with AOT yet.

**Comment by roscheld** [comment]
@gulbdoug Thanks for the reply!

Now I can build the project but when I deploy it, it gives me template parse errors. So I do think I need to change the index file somehow.

```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'widgetId' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'widgetId' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [ERROR ->][(widgetId)]='gridId' [(options)]='gridOptions' [(dataSource)] ='gridData'></ig-grid>"): t@4:9
Can't bind to 'options' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [(widgetId)]='gridId' [ERROR ->][(options)]='gridOptions' [(dataSource)] ='gridData'></ig-grid>"): t@4:31
Can't bind to 'dataSource' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'dataSource' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [(widgetId)]='gridId' [(options)]='gridOptions' [ERROR ->][(dataSource)] ='gridData'></ig-grid>"): t@4:57
'ig-grid' is not a known element:
1. If 'ig-grid' is an Angular component, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
</h1>

[ERROR ->]<ig-grid [(widgetId)]='gridId' [(options)]='gridOptions' [(dataSource)] ='gridData'></ig-grid>"): t@4:0 ; Zone: <root> ; Task: Promise.then ; Value: e {__zone_symbol__error: Error: Template parse errors:
Can't bind to 'widgetId' since it isn't a known property of 'ig-grid'.…, _nativeError: y, __zone_symbol__currentTask: t, __zone_symbol__stack: "Error: Template parse errors:↵Can't bind to 'widge…/polyfills.b22ebf26490bb940fe10.bundle.js:36:667)", __zone_symbol__message: "Template parse errors:↵Can't bind to 'widgetId' si…s' [(dataSource)] ='gridData'></ig-grid>"): t@4:0"} Error: Template parse errors:
Can't bind to 'widgetId' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'widgetId' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [ERROR ->][(widgetId)]='gridId' [(options)]='gridOptions' [(dataSource)] ='gridData'></ig-grid>"): t@4:9
Can't bind to 'options' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [(widgetId)]='gridId' [ERROR ->][(options)]='gridOptions' [(dataSource)] ='gridData'></ig-grid>"): t@4:31
Can't bind to 'dataSource' since it isn't a known property of 'ig-grid'.
1. If 'ig-grid' is an Angular component and it has 'dataSource' input, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
</h1>

<ig-grid [(widgetId)]='gridId' [(options)]='gridOptions' [ERROR ->][(dataSource)] ='gridData'></ig-grid>"): t@4:57
'ig-grid' is not a known element:
1. If 'ig-grid' is an Angular component, then verify that it is part of this module.
2. If 'ig-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
</h1>

[ERROR ->]<ig-grid [(widgetId)]='gridId' [(options)]='gridOptions' [(dataSource)] ='gridData'></ig-grid>"): t@4:0
    at e.y (https://www.site.be/OX-AANKOOP/polyfills.b22ebf26490bb940fe10.bundle.js:36:2553)
    at e [as constructor] (https://www.site.be/OX-AANKOOP/vendor.ac94e36912eb3304b943.bundle.js:534:811)
    at new e (https://www.site.be/OX-AANKOOP/vendor.ac94e36912eb3304b943.bundle.js:954:736)
    at t.parse (https://www.site.be/OX-AANKOOP/vendor.ac94e36912eb3304b943.bundle.js:1220:1522)
    at t._compileTemplate (https://www.site.be/OX-AANKOOP/vendor.ac94e36912eb3304b943.bundle.js:1633:6611)
    at https://www.site.be/OX-AANKOOP/vendor.ac94e36912eb3304b943.bundle.js:1633:4119
    at Set.forEach (native)
    at t._compileComponents (https://www.site.be/OX-AANKOOP/vendor.ac94e36912eb3304b943.bundle.js:1633:4090)
    at i (https://www.site.be/OX-AANKOOP/vendor.ac94e36912eb3304b943.bundle.js:1633:1819)
    at t.invoke (https://www.site.be/OX-AANKOOP/polyfills.b22ebf26490bb940fe10.bundle.js:36:9337)
    at n.run (https://www.site.be/OX-AANKOOP/polyfills.b22ebf26490bb940fe10.bundle.js:36:5061)
    at https://www.site.be/OX-AANKOOP/polyfills.b22ebf26490bb940fe10.bundle.js:36:2128
    at t.invokeTask (https://www.site.be/OX-AANKOOP/polyfills.b22ebf26490bb940fe10.bundle.js:36:10021)
    at n.runTask (https://www.site.be/OX-AANKOOP/polyfills.b22ebf26490bb940fe10.bundle.js:36:5710)
    at a (https://www.site.be/OX-AANKOOP/polyfills.b22ebf26490bb940fe10.bundle.js:36:667)
o @ polyfills.b22ebf2….bundle.js:36
i @ polyfills.b22ebf2….bundle.js:36
r @ polyfills.b22ebf2….bundle.js:36
a @ polyfills.b22ebf2….bundle.js:36
polyfills.b22ebf2….bundle.js:36 y {__zone_symbol__error: Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'widgetId' since it isn't …, rejection: e, promise: t, zone: n, task: t}
```

**Comment by dkamburov** [comment]
This sounds like a third party issue.
Can you check if `mangle: { screw_ie8 : true, keep_fnames: true }` resolves this for you
[https://github.com/angular/angular-cli/pull/1662](https://github.com/angular/angular-cli/pull/1662)

**Comment by roscheld** [comment]
@dkamburov Thanks for the reply but where do I need to add this?

**Comment by dkamburov** [comment]
In webpack.optimize.UglifyJsPlugin

**Comment by roscheld** [comment]
@dkamburov Yeah that I found but in what file?

**Comment by dkamburov** [comment]
It should be in webpack. If you don't have it in your project update the angular cli.

Or in angular-cli.json - similar to this issue https://github.com/angular/angular-cli/pull/5192

**Comment by roscheld** [comment]
@dkamburov I added it to my angular-cli.json and now it complains that property 'uglifyOptions' is not allowed. I still can do ng serve and ng build, but still the same error.

```
ERROR in Unexpected value 'IgGridComponent in ../angular-cli/OX-AANKOOP/node_modules/igniteui-angular2/index.d.ts' declared by the module 'AppModule in ../angular-cli/OX-AANKOOP/src/app/app.module.ts'

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '..\angular-cli\OX-AANKOOP\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

My .angular-cli.json:

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "ox-aankoop"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "../node_modules/ignite-ui/css/structure/infragistics.css",
        "../node_modules/ignite-ui/css/themes/infragistics/infragistics.theme.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/jquery-ui-dist/jquery-ui.min.js",
        "../node_modules/ignite-ui/js/infragistics.core.js",
        "../node_modules/ignite-ui/js/infragistics.lob.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      },
      "uglifyOptions": {
        "mangle": {
            "keep_fnames": true
        }
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```

**Comment by dkamburov** [comment]
Can you update your angular-cli to the latest version?

**Comment by roscheld** [comment]
I updated the angular version but still have the same problem.

```
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.4
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10
```

> My suggestion would be to check the import statements. IgGridComponent should be imported from index.js while the error says it's trying to import it from index.d.ts.

I never tried this because I didn't know where to do it, do you know where and what I need to change so I can check this one?

**Comment by dkamburov** [comment]
I investigated this one and in my opinion it's an issue in the cli. It should resolve when we add support for AOT, until then use the non minified and non compressed bundles.

**Comment by roscheld** [comment]
@dkamburov Ok, thank you for all your help! Do you have an eta for the AOT support?

**Comment by dkamburov** [comment]
I cannot tell for sure when it would be ready, but you can check on issue #133 
Once we got it resolved, we would have AOT support.

**Comment by dkamburov** [comment]
This should be resolved by now.
