### ISSUE TITLE
igcombo does not work properly with multiple selections

### ISSUE THREAD

**Issue by andyalam** [IgniteUI/igniteui-angular2#172]
I'm running into an issue where I'm using igcombo like so:

`<ig-combo
      *ngIf="growerComboOption"
      id="comboGrower"
      [(options)]="growerComboOption"
      [(ngModel)]="growerComboSelected">
</ig-combo>`

In my growerComboOption I'm specifying this property 

`multiSelection: {
            enabled: true,
            addWithKeyModifier: false,
            showCheckboxes: true,
            itemSeparator: ', '
        },`

My growerComboSelected remains the same past one item. If I have 3+ growers selected in my ig-combo, my growerComboSelected always shows the first grower I've added.

Has anyone run into this issue as well?

**Comment by andyalam** [comment]
Any updates on this?

**Comment by andyalam** [comment]
Slightly related but I'm also facing an issue where if I pass in an `initialSelectedItems` option to my growerComboOption, growerComboSelected does not update at all. It seems like the bindings for this component are very wonky.

**Comment by d-georgiev-91** [comment]
Hello adyala,

I will start in reverse order. When you have bound the combo using to ngmodel to specific model, it is only enough to pass default values for that model in the constructor and they will be automatically selected.

I have created a new [pull request](https://github.com/IgniteUI/igniteui-angular2/pull/180) containing the fix for the multi selection isssue. When is merged this issue will be fixed.

Let me know if you need further assistance.

**Comment by andyalam** [comment]
Thanks dgorgee
