### ISSUE TITLE
IgCombo binding issue

### ISSUE THREAD

**Issue by tjeneboe** [IgniteUI/igniteui-angular2#189]
### Description  
We are using ignite ui version 2017.1 w/ igniteui-angular2.  The binding on the combobox is not working as I would expect.  I'm not sure if I'm doing something wrong or there is a bug in the ignite ui code.

### Steps to reproduce  

1.You will need NPM and the Angular CLI installed.
2.Download the attached zip.
3.Run 'npm install' to rehydrate the packages
4.Copy the ignite ui distribution into the following directories.
      misc_modules\ignite-ui\css
      misc_modules\ignite-ui\js
This is to satisfy the following references found in angular-cli.json...
 "styles": [
 "styles.css",
 "../misc_modules/ignite-ui/css/structure/infragistics.css",
 "../misc_modules/ignite-ui/css/themes/infragistics/infragistics.theme.css"
 ],
 "scripts": [
 "../node_modules/jquery/dist/jquery.min.js",
 "../node_modules/jquery-ui-bundle/jquery-ui.min.js",
 "../misc_modules/ignite-ui/js/infragistics.core.js",
 "../misc_modules/ignite-ui/js/infragistics.lob.js"
 ],

5.app.component.html and app.component.ts contains the code of interest. 
6. 'ng serve' the application. 
7. Select a value from the combobox found in column 1, row 2.

### Result  
Column 2 contains standard HTML 'select' controls.  Column 3 contains IgCombo controls.  After executing step #7 above...

The combobox in column 2, row 2 is now enabled (correct behavior).  However, *all* comboboxes in column 3 are enabled (wrong behavior).

### Expected result  
After executing step #7 above...

Only the comboboxes in column 2, row 2 and column 3, row 2 are enabled.   See screenshot.
 
### Attachments  
Screenshot and zip file containing the code have been attached.  
![screenshot](https://user-images.githubusercontent.com/29152359/29588434-5d291d82-8746-11e7-842e-39cfc41905ed.png)
[IgComboBug.zip](https://github.com/IgniteUI/igniteui-angular2/files/1243458/IgComboBug.zip)

**Comment by MayaKirova** [comment]
In this case the problem seems to be that the options of all combos from the last column are bound to the same options object - this.valueComboOptions, so when one of the combo’s changes it’s disabled option (due to the result of isComboEnabled function) and it mutates the options object all of them get the option change applied.
You could prevent that by creating copies of the options, for example:
<ig-combo [widgetId]="'ValueCombo' + i" [options]="getOptions()" …>

  getOptions(){
     return Object.assign({}, this.valueComboOptions);
  }

So that they’ll have separate options object and won’t affect one another.

Let me know if that solves your issue.
