### ISSUE TITLE
IgGrid Not calling CellClick handler in Responsive VerticalRendering layout

### ISSUE THREAD

**Issue by sinclairduong** [IgniteUI/igniteui-angular2#212]
### Description  
When you define a CellClick handler on a IgGrid with Vertical Responsive Rendering, the CellClick handler will only get called in regular mode, not responsive mode.

### Steps to reproduce  

1. Create grid with cellClick handler and responsive feature.
2. Run app and go to page with grid and test that cell click works in regular desktop mode.
3. Make window small enough to trigger vertical rendering and click on a cell

### Result  
The cellClick handler will work when in desktop mode but will not do anything when in responsive mode.

### Expected result  
The cellClick handler works in both desktop and responsive mode.

### Attachments  
(I used someone else's plunkr as a base)
http://plnkr.co/edit/5BnsHr4T2sKE4mhyDmhO?p=preview

**Comment by MayaKirova** [comment]
This appears to be an issue in the IgniteUI control.
It reproduces outside of the angular components that wrap the controls.
I’ve attached a sample for your reference.

I’ve logged a development issue on your behalf with id #246308 for the IgniteUI product.
If you happen to have an active account for the Infragistics.com website I can open a customer case for you and associate it with the development issue so that you may get notified once it has been resolved in the product.

Let me know if there’s anything else I can help you with.
[sample-VerticalRendering.zip](https://github.com/IgniteUI/igniteui-angular2/files/1498889/sample-VerticalRendering.zip)
