### ISSUE TITLE
igTextEditor model updated when clicked outside of Editor

### ISSUE THREAD

**Issue by jkumawat** [IgniteUI/igniteui-angular2#70]
Hello Team,

I have used the igTextEditor Component in my angular 2 application. I have found that it didn't update model value while changing text inside Text Editor rather it change when clicked outside of Editor. 

We would expect to have similar model binding with text editor as in normal HTML Input text control. It should update model value as in real time we try to change the value. 

Can you please have a look into this problem? [Refer: Forum Post](http://www.infragistics.com/community/forums/p/107300/506314.aspx#506314)

Thank you for the wonderful work. Appreciate!  

Warm Regards,

Jeetendra

**Comment by damyanpetev** [comment]
Hello Jeetendra,

While the Ignite UI Editors are intended to be used in place of the default HTML input, they do function differently - due to additional features like max length, excluded characters or limiting to list options, revert if not valid (and then some for more complex editors) the actual value of the control is not updated immediately - that happens on either blur (as you saw) or enter.

Would be fairly easy to allow the Text Editor to update value immediately via the `textChanged` event (kind of like in Knockout). @bazal4o - thoughts?

Could also force-update the numeric editors, but there's no `"immediate"` setting here so it'd be a bit of a change of how those behave. Mask and date partial values are pretty much useless and would really not got for instant updates on those.

- Damyan

**Comment by bazal4o** [comment]
Yes we can add this functionality only for igTextEditor.

**Comment by kdinev** [comment]
@jkumawat Could you test whether the enhancement is what you expect as functionality?

**Comment by kdinev** [comment]
Closing the issue because there has been no feedback for 13 days. I assume the fix resolves the issue.
