### ISSUE TITLE
igPivotGrid - capture rows, columns filters or measures

### ISSUE THREAD

**Issue by sanket360** [IgniteUI/igniteui-angular2#94]
In case of igPivotGrid, when user sets rows / columns / filters / measures etc. Is there a way to capture and apply previously saved settings of pivot grids?

I am looking for ability to save and retrieve pivot configuration done by user. Is this functionality supported by igPivotGrid? If yes, please guide me on this.

I am setting my igPivotGrid with xmlaDataSource like this- 

```
import {Component, Inject, ElementRef, EventEmitter, HostListener} from '@angular/core';
import {IgPivotDataSelectorComponent, IgPivotGridComponent} from "igniteui-angular2";


declare var jQuery: any;

@Component({
  selector: 'my-app',
  //template: '<h1>My First Angular 2 App</h1>'
  template: `
  <h5>Test User Settings:</h5> <button (click)="test()">Test</button>
    
    <div class="row">
<div class="col-md-8">
        <ig-pivot-grid [widgetId]="gridId" [options]="optsGrid" >
        </ig-pivot-grid>
</div>
<div  class="col-md-4">
        <ig-pivot-data-selector [widgetId]="selectorId" [options]="optsSelector" >
        </ig-pivot-data-selector>
</div>

        

        
    </div>
  `,
  directives: [ IgPivotDataSelectorComponent, IgPivotGridComponent]
})

export class AppComponent { 
  private optsGrid: IgPivotGrid;
	private optsSelector: IgPivotDataSelector;
	private selectorId: string;
	private gridId: string;
	private data: any;

constructor() {

  
  this.data =  new jQuery.ig.OlapXmlaDataSource({
			serverUrl: 'http://servername/olap/msmdpump.dll',
      catalog: 'XYZ',
      cube:'ABC'
		});


      this.selectorId = "dataSelector";
      this.gridId = "pivotGrid";

      this.optsGrid = {
        dataSource: this.data,
        height: "100%",
        width: "100%"
      };

      this.optsSelector = {
        dataSource: this.data,
        height: "100%",
        width: "100%"
      };
  }

  test(){
    var test1 = this.data.getMeasure();
    console.log('getMeasure: ' + test1);

    var test2 = this.data.getMeasureList();
    console.log('getMeasure: ' + test2);
  }
}
```

In test method, I get NULL for both getMeasure and getMeasureList. Am I doing something wrong here?  I want to capture setting done by user like selected rows, columns filters or measures. How to achieve this with igPivotGrid?

**Comment by sanket360** [comment]
Could you please respond on this?

**Comment by sanket360** [comment]
This is been pending from week. Could you please respond on this?

**Comment by kdinev** [comment]
@sanket360 This is an open source repository and we have no commitment to respond to, or to fix issues within a given timeframe. We've been very prompt in responding to the issues you have created. If you expect an answer within a certain timeframe, then you can use your Ignite UI license to open a support ticket with us.

https://www.infragistics.com/my-account/submit-support-request

**Comment by dkamburov** [comment]
To restore the state/set new filters/columns/measures of the igPivotGrid you need to recreate it. 
Store it's full options `var obj = $.extend(true, {}, $("#pivotGrid").igPivotGrid("option"))`
Destroy it `$("#pivotGrid").igPivotGrid("destroy")`
Recreate it `$("#pivotGrid").igPivotGrid(obj)`. And into the recreation part different filters/columns/measures can be applied

**Comment by sanket360** [comment]
After using this statement-
`var obj = $.extend(true, {}, $("#pivotGrid").igPivotGrid("option"))`

How do I read filters/columns/measures of the igPivotGrid from obj variable?

If I try like this-
```
var obj = $.extend(true, {}, $("#pivotGrid").igPivotGrid("option"))
    console.log('obj.option ' + this.obj.option);
    console.log('obj.options ' + this.obj.options);
    console.log('obj.getMeasure ' + this.obj.getMeasure);
    console.log('obj.getMeasureList ' + this.obj.getMeasureList);
    console.log('obj.getDimension ' + this.obj.getDimension);
```
it gives me undefined for all 5 lines.

**Comment by dkamburov** [comment]
`$("#pivotGrid").igPivotGrid("option")` - This will give you the entire igPivotGrid configuration options
If you want specifically the filters/columns and measures you need to extract those from the dataSource of the pivotgrid since they are properties of the data source:
[$("#pivotGrid").igPivotGrid("option", "dataSource").columnAxis()](http://www.igniteui.com/help/api/2016.1/ig.OlapFlatDataSource#methods:columnAxis)

[$("#pivotGrid").igPivotGrid("option", "dataSource").filters()](http://www.igniteui.com/help/api/2016.1/ig.OlapFlatDataSource#methods:filters)

[$("#pivotGrid").igPivotGrid("option", "dataSource").measures()](http://www.igniteui.com/help/api/2016.1/ig.OlapFlatDataSource#methods:measures)

or even getMeasure(), getMeasureList() and getDimension() the ones you specified

**Comment by sanket360** [comment]
I tried to capture like this-

```
    console.log('getMeasure(): ' + $("#pivotGrid").igPivotGrid("option", "dataSource").getMeasure());
    console.log('getMeasureList(): ' + $("#pivotGrid").igPivotGrid("option", "dataSource").getMeasureList());
    console.log('getDimension(): ' + $("#pivotGrid").igPivotGrid("option", "dataSource").getDimension());
```
But all 3 are null.

Am I missing anything here?

**Comment by dkamburov** [comment]
Ok, I'll assume you are using [http://igniteui.github.io/igniteui-angular2/samples/igPivotGrid-FlatDataSource/igPivotGrid-FlatDataSource.html](http://igniteui.github.io/igniteui-angular2/samples/igPivotGrid-FlatDataSource/igPivotGrid-FlatDataSource.html) sample and answer based on it, because it also returns null on all of the calls you described.

1. `$("#pivotGrid").igPivotGrid("option", "dataSource").getMeasure()` -> returns null, because it requires an argument, in order to get the measure you want, you have to pass it. For this sample it should be:
`$("#pivotGrid").igPivotGrid("option", "dataSource").getMeasure("[Measures].[UnitsSold]")`. More info here - [http://www.igniteui.com/help/api/2016.1/ig.OlapFlatDataSource#methods:getMeasure](http://www.igniteui.com/help/api/2016.1/ig.OlapFlatDataSource#methods:getMeasure)

2. `$("#pivotGrid").igPivotGrid("option", "dataSource").getMeasureList()` -> returns null, because into the sample, there is only one measure specifed and $.ig.MeasureList is not going to assembled for only one measure, measures should more than one. You can see this
into the description of the API method getMeasureList() - [http://www.igniteui.com/help/api/2016.1/ig.OlapFlatDataSource#methods:getMeasureList](http://www.igniteui.com/help/api/2016.1/ig.OlapFlatDataSource#methods:getMeasureList)
You can review the other sample for the igPivotGrid [http://igniteui.github.io/igniteui-angular2/samples/igPivotGrid-XmlaDataSource/igPivotGrid-XmlaDataSource.html](http://igniteui.github.io/igniteui-angular2/samples/igPivotGrid-XmlaDataSource/igPivotGrid-XmlaDataSource.html) and see that there is two measures and you can take advantage getMeasureList() there

3. `$("#pivotGrid").igPivotGrid("option", "dataSource").getDimension()` -> returns null, because it also requires an argument the name of the dimension. For example:
`$("#pivotGrid").igPivotGrid("option", "dataSource").getDimension("[Date]")`. More info here http://www.igniteui.com/help/api/2016.1/ig.OlapFlatDataSource#methods:getDimension

**Comment by sanket360** [comment]
No, I am using OlapXmlaDataSource

**Comment by dkamburov** [comment]
This doesn't matter. The rules still apply.

I used this data:
```
this.data = new jQuery.ig.OlapXmlaDataSource({
  serverUrl: 'http://sampledata.infragistics.com/olap/msmdpump.dll',
  catalog: 'Adventure Works DW Standard Edition',
  cube: 'Adventure Works',
});
```

I've dragged from the pivotDataSelector two measures, one Column and one Row and here's the output:

![screenshot](https://cloud.githubusercontent.com/assets/1182001/19143480/efb27536-8bac-11e6-90ac-60c923928396.png)

**Comment by sanket360** [comment]
ok thanks and how do I use measures?

If I do this
`console.log('measures: ' + $("#pivotGrid").igPivotGrid("option", "dataSource").measures());`
This gives me object like shown in above screenshot.

How do I read properties of measures like- name, uniquename etc?

**Comment by dkamburov** [comment]
[measures()](http://www.igniteui.com/help/api/2016.1/ig.OlapFlatDataSource#methods:measures) is returning an array of objects of type [$.ig.Measure](http://www.igniteui.com/help/api/2016.1/ig.Measure).

You can inspect the [$.ig.Measure methods](http://www.igniteui.com/help/api/2016.1/ig.Measure#methods) to see how to get use of it.

**Comment by sanket360** [comment]
great thanks :+1:
