### ISSUE TITLE
Cannot compile using angular-cli and webpack

### ISSUE THREAD

**Issue by mharrington622** [IgniteUI/igniteui-angular2#96]
## Steps to reproduce:
1. Install angular-cli (make sure nodejs and npm are up to date)
2. Scaffold a new project with "ng new <name>"
3. Run "npm install igniteui-angular2"
4. Import a component from igniteui-angular2 to build into webpack
5. Run "ng serve"
## Issue:

While webpack tries to compile with the typings, you receive errors saying:

> igniteUIWebpackTest\node_modules\igniteui-angular2\igniteui.angular2.d.ts:59:56
> Cannot find name 'IgGrid'.

This occurs for each of the controls.  If you try to implement the component and visit the page, you receive the same errors in the browser.

**Comment by SamDLT** [comment]
It seems that there are two seperate issues here. The type definitions files are incorrect and contain incomplete type definitions which will result in compiler errors when webpack is creating the bundle. Also, the file that is being distributed which contains the Angular 2 components uses System.register which is a problem as my understanding is that Webpack understands AMD and CommonJS modules out of the box and will not understand System.register.

Also, given that the .ts files are not being distributed, Typescript will not find the appropriate module when doing this:

```javascript
Import SomeComponent from 'igniteui-angular2';
```

As documented [here](https://www.typescriptlang.org/docs/handbook/module-resolution.html), Typescript will attempt to search for these directories:

/node_modules/igniteui-angular2.ts
/node_modules/igniteui-angular2.d.ts

This will fail and a module will not be found which will also cause the bundle to fail.

So we are left to using an absolute path to import the igniteui-angular2 components:

```javascript
import SomeComponent from '../../node_modules/igniteui-angular2/igniteui.angular2.js';
```

Which still won't work with Webpack as it is using System.register :(

Currently, angular-cli is the suggested development path and defaults to using Webpack for module bundling (RIP SystemJS) so I feel this scenario should absolutely be supported.

My impression is that the necessary steps to solve this would be:

1) Distribute Typescript file such that the igniteui-angular2 folder will contain an igniteui-angular2.ts file which will then be compiled and bundled by Webpack
2) Not all users will be using Typescript, even if it will be a minority, therefore, we should distribute a JS file that uses the more widely used CommonJS or AMD module syntax rather than System.register.

**Comment by dkamburov** [comment]
The issue occurs, because it is not possible to load igniteui.d.ts typescript definitions.

One way to resolve is to specify the igniteui.d.ts inside the typings.json. But this approach is not recommended, it requires additional manual configurations.

The other approach is to add igniteui.d.ts in DefinetlyTyped, so it could be installed through `npm install @types/igniteui ` and add it as devDependency. But before adding this dependency we need to distribute igniteui typing definitions as a package.
This will allow installing igniteui-angular2 as a [third party library in projects created through angular-cli](https://github.com/angular/angular-cli#3rd-party-library-installation).

**Comment by kdinev** [comment]
@dkamburov Should I be closing this issue? I tagged a new version after merging.

**Comment by NilsQuirmbach** [comment]
It is not yet working, just tested it but it's pretty easy to fix.

There are two issues:

1. Node can't find the ignite-angular.js file at all. One solution is to rename the igniteui.angular2.js file to index.js, the other one would be to set the main property in the package.json file.

2. The igniteui.d.ts can't be found. I just added a reference tag on top at the igniteui.angular2.d.ts.
///<reference path="igniteui.d.ts" />

Now I am able to build the project.
[igniteui-angular2.zip](https://github.com/IgniteUI/igniteui-angular2/files/542041/igniteui-angular2.zip)

**Comment by dkamburov** [comment]
We shouldn't close this one yet.

Triple-slash references is one way to resolve this, but there are some IDE-s, which don't like having them.
And since igniteui.d.ts are typings definitions, should be distributed as such(in separate typings package) and once that's done, we'll be able to add them as devDependency.

**Comment by dkamburov** [comment]
I've added a [pull request](https://github.com/typings/registry/pull/848) to the typings/registry

**Comment by dkamburov** [comment]
The pull request to typings/registry was closed. IgniteUI typings will be imported and distributed with the package. More info [here](https://github.com/typings/registry/issues/848)

**Comment by dkamburov** [comment]
Should be resolved using the latest npm package 1.1.2

**Comment by NilsQuirmbach** [comment]
It works! There are still some issues left when including the infragistic css-files from the igniteui npm package.

ERROR in ./~/css-loader!./~/postcss-loader!./~/igniteui/css/infragistics.css
Module not found: Error: Can't resolve './images/igVideoPlayer/igVPBookmarkSprite.png' in 'D:\TFS\Development\NextPlatform\Ibs.QProject\Qms.QProject.Shell\node_modules\igniteui\css'
 @ ./~/css-loader!./~/postcss-loader!./~/igniteui/css/infragistics.css 6:1628-1684 6:1775-1831 6:1927-1983 6:145338-145394 6:145524-145580 6:145715-145771 6:148163-148219 6:148336-148392 6:148512-148568
 @ ./~/igniteui/css/infragistics.css
 @ multi styles

**Comment by dkamburov** [comment]
This is not a problem related to this issue.
I've included references of IgniteUI


    <link href="http://cdn-na.infragistics.com/igniteui/2016.2/latest/css/themes/infragistics/infragistics.theme.css" rel="stylesheet" />
    <link href="http://cdn-na.infragistics.com/igniteui/2016.2/latest/css/structure/infragistics.css" rel="stylesheet" />

    <script src="http://ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.8.3.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>

    
    <script src="http://cdn-na.infragistics.com/igniteui/2016.2/latest/js/infragistics.core.js"></script>
    <script src="http://cdn-na.infragistics.com/igniteui/2016.2/latest/js/infragistics.lob.js"></script>

to the index.html of the angular-cli project and I was able to run a igVideoPlayer without the described error.

Make sure the referred png that is there.
You can download [IgniteUI package](https://www.npmjs.com/package/ignite-ui) or download the full product from [igniteui.com](https://igniteui.com/download).

>Note: If you use npm, make sure you are not downloading the [https://www.npmjs.com/package/ignite-ui](https://www.npmjs.com/package/igniteui), 
instead of [https://www.npmjs.com/package/ignite-ui](https://www.npmjs.com/package/ignite-ui).
This is the correct one -> [https://www.npmjs.com/package/ignite-ui](https://www.npmjs.com/package/ignite-ui)

**Comment by NilsQuirmbach** [comment]
I kinda disagree, the way you described is just a workaround.
To include a external stylesheet you should add it the the angular-cli.json.

https://github.com/angular/angular-cli#global-library-installation

![image](https://cloud.githubusercontent.com/assets/22655797/20138320/fd0fdcf8-a67f-11e6-8729-56110fac7dad.png)

**Comment by dkamburov** [comment]
Can you attach a sample so we can review it?

**Comment by NilsQuirmbach** [comment]
Sure, here it is:
https://github.com/NilsQuirmbach/cli-ignite-ui

**Comment by dkamburov** [comment]
I investigated it. And I was right. It is a bug into the ignite-ui package and it is not related to this issue.

These paths **../images/igTooltip/igTooltipBackground.svg** into the .css files are wrong, should be changed to **../images/igPopover/igPopoverBackground.svg**

I'm sending you the modified files and I'll do a pull request to ignite-ui repo afterwards.

So that you can replace them into your repo, while waiting my pull request to be merged.

Their paths are:
 - cli-ignite-ui-master\node_modules\ignite-ui\css\themes\infragistics\infragistics.theme.css
 - cli-ignite-ui-master\node_modules\ignite-ui\css\structure\infragistics.css


[modified files.zip](https://github.com/IgniteUI/igniteui-angular2/files/580985/modified.files.zip)

**Comment by NilsQuirmbach** [comment]
Okay, thanks. That works for me for now.

**Comment by dkamburov** [comment]
Here's my [pull request](https://github.com/IgniteUI/ignite-ui/pull/518) on the issue I was talking about.

I guess we can close this issue now.
