### ISSUE TITLE
How to access grid features via the angular 2 wrapper

### ISSUE THREAD

**Issue by bonejon** [IgniteUI/igniteui-angular2#98]
The ignite grid has a lot of functionality available via jQuery, how can we access these interfaces via the angular 2 wrappers?
An example would be the following:

<code>$("#grid1").igGridUpdating("updateRow", 0, { Name: "Maria" });</code>

Thanks, Jon.

**Comment by kdinev** [comment]
@bonejon We're actually considering including proxies for the API of all widgets in order to make the developer experience better within the context of an Angular application. At this point we still don't have a clear timeline on when we would be able to deliver these, but I can tell you this would be the next thing we will be working on.

**Comment by MayaKirova** [comment]
Hi Konstantin,

I’ve created a POC sample with a possible implementation where you can invoke the methods on the related feature’s directive, which you can access either via getting a reference to the directive:

```
 @ViewChild(IgGridSortingFeature) sorting:IgGridSortingFeature;

ngAfterViewInit() {
this.sorting.sortColumn("ProductID", "descending");
}
```

Or via the Grid’s component:
```
  @ViewChild("grid1") myGrid: IgGridComponent;

this.myGrid.featuresList.filtering.filter( [{fieldName: "ProductNumber", expr: "b", cond: "contains", logic: "AND"}]);
```

You can call any feature method in this way, however for the POC sample I’ve only exposed some of the methods in the component itself so that they can have Intellisense.
We can generate the additional definitions from the API Parser  for the actual implementation.
[sample_POC.zip](https://github.com/IgniteUI/igniteui-angular2/files/689938/sample_POC.zip)

**Comment by kdinev** [comment]
@MayaKirova I definitely like the first syntax better, but my understanding is that it would be hard to distinguish between two different grids with sorting features. Let's meet to discuss this POC. It seems likely that we'd go with the second syntax, but let's discuss this first.

**Comment by kdinev** [comment]
Update from the meeting:

1. Both of the proposed syntaxes will be available.
2. Accessing features directly by name (e.g. `this.sorting.doStuff()`) will be available only if the named feature is available as a `ViewChild`

**Comment by boogher** [comment]
I think having typed functions, properties, and return objects is important. I started using the igGrid and I am using the Angular_API branch which has most of the functions and properties exposed. However not everything is strongly typed yet and I am having to access through casting as <any>. Here is an example:

`
@ViewChild('myGrid') myGrid: IgGridComponent;
...
myFunction(){
var selectedrow = this.myGrid.selectedRow();
       var selectedIndex = (<any>selectedrow).index;
       var availUnit = <AvailableUnit>(<any>this.myGrid).dataSourceObject()[selectedIndex];
}
`

selectedRow doesn't return a typed object so I have to use the <any> cast. If I was to type .Index where the case is wrong I wouldn't get an error until run time. The same is true with dataSourceObject which is a function that you would expect to be a property of type array. 
Wouldn't it be nice if I could write:
`
@ViewChild('myGrid') myGrid: IgGridComponent;
...
myFunction(){
var selectedrow : IgRow = this.myGrid.selectedRow;
var selectedUnit = <AvailableUnit>selectedRow.DataObject

or even better:  var selectedUnit = <AvailableUnit> this.myGrid.selectedRow.DataObject
`

**Comment by kdinev** [comment]
@MayaKirova I believe we should get what you have pulled into master. I will then tag as a pre-release version, so users can test it without having to pull your branch. We can then map out all the improvements and work on them to get it to a release state.

@boogher confirms that we need a more complete TS defs for Ignite UI. Just FYI, the shortage of types comes from the fact that Ignite UI precedes TypeScript, so we're going JS -> TS, instead of TS -> JS, which would be what the common expectation is.
